### ISSUE TITLE
[FEATURE] course and module

### ISSUE THREAD

**Issue by steffenhls** [integrationsseminar/learning-analytics-backend#18]
**Wie ist es aktuell:**
Aktuell wird nicht differenziert ob es sich um ein Modul (Bsp. Integrationsseminar) oder Kurs (Bsp. WWI20SEA) handelt.

**Wie sollte es sein:**
Ein Dozent müsste wissen welcher Kurs das ist und ein Student welches Modul.

**Zusätzliche Anmerkungen:**

**Comment by lumaghg** [comment]
@STAT1C-Sy ich bin mal so frei

**Comment by STAT1C-Sy** [comment]
@steffenhls bei uns gibt es keine Kurse in dem Sinne

**Comment by lumaghg** [comment]
@STAT1C-Sy das ist aber so in den Mockups wenn ich mich richtig erinnere

**Comment by STAT1C-Sy** [comment]
@lumaghg wir können das gerne in den Profilinformationen ergänzen, aber bei mehr würde ich nicht mitgehen weil das sonst zu viel Aufwand ist

**Comment by lumaghg** [comment]
Ja ich hätte da jetzt einfach ein Extrafeld hinzugefügt und rollenabhängig WWI20SEA oder Integrationsseminar als name angezeigt

**Comment by STAT1C-Sy** [comment]
rollenabhängig?

**Comment by lumaghg** [comment]
mit $project und moduleName und courseName => name

**Comment by lumaghg** [comment]
Ja es geht doch darum, dass der Dozent WWI20SEA lesen soll und der Student Integrationsseminar, weil das jeweils die interessanten Informationen sind

**Comment by lumaghg** [comment]
Also so hatte ich das verstanden

**Comment by STAT1C-Sy** [comment]
hä der Dozent kann den Kurs doch einfach  Integrationsseminar WWI20SEA nennen sehe hier das Problem nicht

**Comment by lumaghg** [comment]
Joa schon

**Comment by lumaghg** [comment]
@steffenhls ?

**Comment by STAT1C-Sy** [comment]
Also sehe hier definitiv keinen need zum hinzufügen von einem neuen Datenmodell das ist Overkill

**Comment by lumaghg** [comment]
Ja würde ich zustimmen, hab nicht so viel nachgedacht als Steffen das gestern geöffnet hat sry

**Comment by STAT1C-Sy** [comment]
Ja No Problem ist ja wichtig das wir das einmal diskutieren, meine mich erinnern zu können das wir das schonmal diskutiert hatten

**Comment by steffenhls** [comment]
das halt giga hässlich wenn dieses tag immer beides drin hat

**Comment by STAT1C-Sy** [comment]
welches Tag?

**Comment by steffenhls** [comment]
kann man beim kurs anlegen nicht zwei felder haben mit kurs und modul und ich nehme je nach rolle dann eins von beidem raus?

**Comment by STAT1C-Sy** [comment]
Jein das geht an sich schon aber das können zB gewisse Dozenten nicht eintragen wenn zB der Korsta damit seinen Bibliotheksquatsch macht dann geht das zB nicht also das nimmt flexibilität aus dem Prozess und nährt uns stärker an moodle an

**Comment by steffenhls** [comment]
ja true, aber wenn der 5 kurse hat und die alle bibliotheksquatsch nennt kann der die auch nicht differenzieren. also der hat safe noch irgendeine ergänzung

**Comment by STAT1C-Sy** [comment]
ja exakt aber würde die einfach im Titel eintragen also der nennt die dann zB bibliotheksquatsch 23.10.2020
