### ISSUE TITLE
[FEATURE] Die Statistik für den Lernverlauf fehlen

### ISSUE THREAD

**Issue by MaikKBRNK** [integrationsseminar/learning-analytics-backend#23]
**Wie ist es aktuell:**
Aktuell kann ich nicht alle Daten auslesen, die ein User angegeben hat.

**Wie sollte es sein:**
Ich sollte alle Daten bekommen können, um so den Lernverlauf darstellen zu können (siehe MockUps).

**Zusätzliche Anmerkungen:**

**Comment by lumaghg** [comment]
Außerdem erstmal den Lernfortschritt implementiert

**Comment by lumaghg** [comment]
Ich mach das morgen
